#!/usr/bin/env zsh

conf="$HOME/.config"
scp="$HOME/.scripts"

DEPS_PACMAN=(
    "arandr"
    "dunst"
    "feh"
    "fzf"
    "git"
    "i3-gaps"
    "nasm"
    "playerctl"
    "pulseaudio"
    "qutebrowser"
    "redshift"
    "surf"
    "sxhkd"
    "zathura"
    "zathura-pdf-mupdf"
    "zsh"
)

DEPS_AUR=(
    "brave"
    "polybar"
    "pulseaudio-ctl"
)

# prints the usage of this script
print_usage () {
    printf "Usage:\n\t-c\tinstall just the configs\n\t-s\tinstall just the scripts\n\t-d\tinstall just the dependencies of this setup\n\t-a\tinstall configs, scripts and dependencies\n"
}

# install config to $conf
install_config () {
    # ----------------- configs -----------------
    mkdir -p $conf

    # ZSH
    cp config/zsh/zshrc ~/.zshrc
    cp config/zsh/nelson.zsh-theme ~/.oh-my-zsh/themes
    cp config/zsh/alias ~/.alias
    # dunst
    cp -r config/dunst $conf
    # i3
    cp -r config/i3 $conf
    # Polybar
    cp -r config/polybar $conf
    # sxhkd
    cp -r config/sxhkd $conf
    # Wallpaper
    cp config/wallpaper.jpg ~/.wallpaper.jpg

    echo "DONE: installing configs"
}

# install scripts to $scp
install_scripts () {
    # ----------------- scripts -----------------
    mkdir -p $scp

    cp -r scripts/network $scp
    cp -r scripts/startup $scp
    cp -r scripts/util $scp
    cp -r scripts/polybar $scp

    echo "DONE: installing scripts"
}

install_dependencies () {

    # Installs from official Repos
    echo "----------- install deps via pacman -----------"
    sudo pacman -S $DEPS_PACMAN


    echo "----------- install deps from aur -----------"
    # Installs from AUR
    yay -S $repos_aur

    # installs via git
    cd ~/
    mkdir -p Programms
    cd Programms

    echo "--------------- dmenu ---------------\n"
    git clone https://github.com/einzigartigername/dmenu
    cd dmenu
    sudo make install clean
    cd ..
    echo "DONE: installing dmenu\n\n"

    echo "--------------- st ---------------\n"
    git clone https://github.com/LukeSmithxyz/st.git
    cd st
    sudo make install clean
    cd ..
    echo "DONE: installing st\n\n"

    echo "--------------- yay ---------------\n"
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -sic
    cd ..
    echo "DONE: installing yay\n\n"

    echo "--------------- oh-my-zsh ---------------\n"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    echo "DONE: installing oh-my-zsh\n\n"

    echo "--------------- xlight ---------------\n"
    https://github.com/einzigartigerName/xlight.git
    cd illuminate
    make && sudo make install clean
    cd ..
    echo "DONE: installing xlight\n\n"

    echo "----------- DONE -----------"
}




if [ -z "${1// }" ];
then
    print_usage
    exit
fi

# flags for install opts
FLAG_CONFIG=0
FLAG_DEPS=0
FLAG_SCRIPT=0

while getopts "acsd" opt;
do
    case $opt in
        a)  
            # install all
            FLAG_CONFIG=1
            FLAG_DEPS=1
            FLAG_SCRIPT=1
            ;;
        c)
            # install config
            FLAG_CONFIG=1
            ;;
        s)
            # install scripts
            FLAG_SCRIPT=1
            ;;
        d)
            # install dependencies
            FLAG_DEPS=1
            ;;
    esac
done

if [[ "$FLAG_DEPS" -eq 1 ]];
then
    install_dependencies
fi

if [ "$FLAG_CONFIG" -gt 0 ]; then
    install_config
fi

if [[ "$FLAG_SCRIPT" -eq "1" ]];
then
    install_scripts
fi