#!/usr/bin/env zsh

conf="$HOME/.config"
scp="$HOME/.scripts"

DEPS_PACMAN=(
    "git"
    "nasm"
    "i3-gaps"
    "sxhkd"
    "dunst"
    "firefox"
    "qutebrowser"
    "surf"
    "pulseaudio"
    "feh"
    "fzf"
    "zathura"
    "zathura-pdf-mupdf"
    "redshift"
    "arandr"
)

DEPS_AUR=(
    "polybar"
    "playerctl"
    "pulseaudio-ctl"
)

# prints the usage of this script
print_usage () {
    printf "Usage:\n\t-c\tinstall just the configs\n\t-s\tinstall just the scripts\n\t-d\tinstall just the dependencies of this setup\n\t-a\tinstall configs, scripts and dependencies\n"
}

# install config to $conf
install_config () {
    # ----------------- configs -----------------
    mkdir -p $conf

    # ZSH
    cp config/zsh/zshrc ~/.zshrc
    cp config/zsh/nelson.zsh-theme ~/.oh-my-zsh/themes
    cp config/zsh/alias ~/.alias
    # dunst
    cp -r config/dunst $conf
    # i3
    cp -r config/i3 $conf
    # Polybar
    cp -r config/polybar $conf
    # sxhkd
    cp -r config/sxhkd $conf
    # Wallpaper
    cp config/wallpaper.jpg ~/.wallpaper.jpg

    echo "DONE: installing configs"
}

# install scripts to $scp
install_scripts () {
    # ----------------- scripts -----------------
    mkdir -p $scp

    cp -r scripts/network $scp
    cp -r scripts/startup $scp
    cp -r scripts/util $scp
    cp -r scripts/polybar $scp

    echo "DONE: installing scripts"
}

install_dependencies () {

    # Installs from official Repos
    printf "----------- install deps via pacman -----------"
    repos=""
    for item in ${DEPS_PACMAN[*]}
    do
        repos="$repos $item"
    done
    sudo pacman -S $repos


    printf "----------- install deps from aur -----------"
    # Installs from official Repos
    repos_aur=""
    for item in ${DEPS_AUR[*]}
    do
        repos_aur="$repos_aur $item"
    done
    yay -S $repos_aur

    # installs via git
    cd ~/
    mkdir -p Programms
    cd Programms

    printf "--------------- dmenu ---------------\n"
    git clone https://github.com/einzigartigername/dmenu
    cd dmenu
    sudo make install clean
    cd ..
    printf "DONE: installing dmenu\n\n"

    printf "--------------- st ---------------\n"
    git clone https://github.com/LukeSmithxyz/st.git
    cd st
    sudo make install clean
    cd ..
    printf "DONE: installing st\n\n"

    printf "--------------- yay ---------------\n"
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -sic
    cd ..
    printf "DONE: installing yay\n\n"

    printf "--------------- oh-my-zsh ---------------\n"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    printf "DONE: installing oh-my-zsh\n\n"

    printf "--------------- xlight ---------------\n"
    https://github.com/einzigartigerName/xlight.git
    cd illuminate
    make && sudo make install clean
    cd ..
    printf "DONE: installing xlight\n\n"

    printf "----------- DONE -----------"
}

case $1 in
    "-a" )
        install_dependencies
        install_config
        install_scripts
        exit;;
    "-c" )
        install_config
        exit;;
    "-s" )
        install_scripts
        exit;;
    "-d" )
        install_dependencies
        exit;;
    * )     print_usage;;
esac
