#!/usr/bin/env zsh

selection="$(echo -e "Logout\nShutdown\nRestart" | dmenu -i -p "What do you want to do?")"
if [ -z "${selection// }" ]; then
    exit
fi

action=""

case $selection in
	"Logout" )		action="Logout";;
	"Shutdown" )	action="Shutdown";;
	"Restart" )		action="Restart";;
	* )				exit;;
esac

responds="$(echo -e "Yes\nNo" | dmenu -i -p "$action?")"
if [ -z "${responds// }" ]; then
    exit
fi

if [ $responds = "Yes" ]; then
	case $selection in
		"Logout" )		i3-msg exit;;
		"Shutdown" )	poweroff -force;;
		"Restart" )		reboot now;;
		* )				exit;;
	esac
fi
