#!/usr/bin/env zsh

project_dir="$HOME/TUM/"

selection=$(ls -D $project_dir | dmenu -i -l 7 -p "Project to open:")
if [ -z "${selection// }" ]; then
    exit
fi

cd "$project_dir$selection"
st &

if [ "$selection" = "Zusammenfassungen" ]; then
    code . &
else
    zathura &
fi