#!/usr/bin/env zsh

#   Bookmark Format:
#   <name> <url> [browser]

# bookmarks
file=$1

remove () {
    grep "$1 " $file -v > tmp_bm && mv tmp_bm $file
}

# select between insert and remove
mode="$(echo -e "Insert\nRemove" | dmenu -i -p "Bookmarks - Select Action:")"

# Remove and exit
if [ $mode = "Remove" ]; then
    remove "$(cat $file | awk '{print $1}' | dmenu -i -l 7)"
    exit
fi

# get name to display as bookmark
name="$(echo "" | dmenu -p "Name:")"

# get url for bookmark
url="$(echo "" | dmenu -p "URL:")"

# change default brower
bool="$(echo -e "yes\nno" | dmenu -p "Change default Browser?")"

browser=""
if [ $bool = "yes" ]; then
    browser="$(echo -e "Firefox\nQutebrowser" | dmenu -i -p "Select Default Browser:")"

    case $browser in
        "Firefox" )     browser="firefox";;
        "Qutebrowser" ) browser="qute";;
    esac
fi

# Write bookmark
remove $name
echo "$name $url $browser" >> $file