# oh-my-zsh Location
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="nelson"

# Plugins
plugins=(
    rustup
    cargo
    zsh-completions
)

# Config
source $ZSH/oh-my-zsh.sh

# opam configuration
test -r $HOME/.opam/opam-init/init.zsh && . $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# haskell
export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

# Alias
source ~/.alias

# Export vars
export EDITOR=nvim
export PAGER=most
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"

autoload -U compinit && compinit
