# oh-my-zsh Location
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="nelson"

# Plugins
plugins=(git)

# Config
source $ZSH/oh-my-zsh.sh

# opam configuration
test -r $HOME/.opam/opam-init/init.zsh && . $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# Alias
source ~/.alias
